###
POST http://localhost:4000/auth/login
Content-Type: application/json

{ 
    "phone": "0835059053",
    "password": "123" 
}


###
POST http://localhost:4000/auth/register
Content-Type: application/json

{ 
    "phone": "1234",
    "password": "123" 
}

###
POST http://localhost:4000/auth/generate-code
Content-Type: application/json

{ 
    "email": "phucthai0108@gmail.com"
}