###
GET http://localhost:4000/order/get-all
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsImRpc3RyaWN0Ijo1LCJwcm92aW5jZSI6NCwid2FyZCI6NiwiY2FydCI6W10sIndpc2giOltdfSwiaWF0IjoxNjU4NDM1ODkzLCJleHAiOjE2NTg2MDg2OTN9.6xtoNqlHFtyj9pEgxEXRxZAX-Zc7rqc87rf144eo4qQ


###
POST http://localhost:4000/order/create
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiJwaHVjdGhhaTAxMDhAZ21haWwuY29tIiwiZnVsbG5hbWUiOiJSb3VzZVB1IiwiZ2VuZGVyIjoiTmFtIiwiYWRkcmVzcyI6IjM3bG9lIiwiY21uZCI6IiIsInJvbGUiOjEwMDAsImJpbyI6IkNow6BvIG3hu6tuZyDEkeG6v24gdHJhbmcgY8OhIG5ow6JuIHRyw6puIMSQ4buTIENoxqFpIFhlIGPhu6dhIHTDtGkhIiwicmVjZWlwdCI6W10sImNyZWF0ZUF0IjoiMjAyMi0wNi0yNVQxODoyMjo0Ni4wNDJaIiwiX192IjowLCJkaXN0cmljdCI6MTQ0NywicHJvdmluY2UiOjIwMiwid2FyZCI6MjA1MDksImNhcnQiOltdLCJ3aXNoIjpbeyJwcm9kdWN0X2lkIjoiNjJiZDc5YzlkY2NjYjZlZTlmYWY5Y2Q5IiwiX2lkIjoiNjJmZTUzMjQzY2FkYjNjNjA3MjE3ODA1In1dfSwiaWF0IjoxNjYxMDc0NzI0LCJleHAiOjE2NjEyNDc1MjR9.HMJIzMryqpBi22wvqAyYRgNlV4TV-8Sz2czcax2_qm4
Content-Type: application/json

{ 
    "products": [
        {
            "idProduct": "62bd79c9dcccb6ee9faf9cd9",
            "priceAtBuy": 2300000,
            "typeId": "62bd79c9dcccb6ee9faf9cda",
            "quantity": 2,
            "total": 4600000
        },
        {
            "idProduct": "62bdae4e7d37554df2767afd",
            "priceAtBuy": 1400000,
            "typeId": "62bdae4e7d37554df2767afe",
            "quantity": 3,
            "total": 4200000
        }
    ],
    "ship": 100000,
    "total": 8800000,
    "payment": 1
}


###
POST http://localhost:4000/order/pay
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiJwaHVjdGhhaTAxMDhAZ21haWwuY29tIiwiZnVsbG5hbWUiOiJSb3VzZVB1IiwiZ2VuZGVyIjoiTmFtIiwiYWRkcmVzcyI6IjM3bG9lIiwiY21uZCI6IiIsInJvbGUiOjEwMDAsImJpbyI6IkNow6BvIG3hu6tuZyDEkeG6v24gdHJhbmcgY8OhIG5ow6JuIHRyw6puIMSQ4buTIENoxqFpIFhlIGPhu6dhIHTDtGkhIiwicmVjZWlwdCI6W10sImNyZWF0ZUF0IjoiMjAyMi0wNi0yNVQxODoyMjo0Ni4wNDJaIiwiX192IjowLCJkaXN0cmljdCI6MTQ0OCwicHJvdmluY2UiOjIwMiwid2FyZCI6MjA2MDcsImNhcnQiOltdLCJ3aXNoIjpbXX0sImlhdCI6MTY1ODY0Mzg2OCwiZXhwIjoxNjU4ODE2NjY4fQ.9l6d2oBLF6-8UtpBqU40JeQlOB6ksuxnlTyhvkBfqrE
Content-Type: application/json

{ 
   "id": "62dce91e1b627e11a3545d7f"
}