###
GET http://localhost:4000/order/get-all
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsImRpc3RyaWN0Ijo1LCJwcm92aW5jZSI6NCwid2FyZCI6NiwiY2FydCI6W10sIndpc2giOltdfSwiaWF0IjoxNjU4NDM1ODkzLCJleHAiOjE2NTg2MDg2OTN9.6xtoNqlHFtyj9pEgxEXRxZAX-Zc7rqc87rf144eo4qQ
`

###
POST http://localhost:4000/order/create
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsImRpc3RyaWN0Ijo1LCJwcm92aW5jZSI6NCwid2FyZCI6NiwiY2FydCI6W10sIndpc2giOltdfSwiaWF0IjoxNjU4NDM1ODkzLCJleHAiOjE2NTg2MDg2OTN9.6xtoNqlHFtyj9pEgxEXRxZAX-Zc7rqc87rf144eo4qQ
Content-Type: application/json

{ 
    "products": [
        {
            "idProduct": "62bd79c9dcccb6ee9faf9cd9",
            "priceAtBuy": 12092801,
            "typeId": "62bd79c9dcccb6ee9faf9cda",
            "quantity": 1,
            "total": 4005000
        },
        {
            "idProduct": "62bdae4e7d37554df2767afd",
            "priceAtBuy": 12412344,
            "typeId": "62bdae4e7d37554df2767afe",
            "quantity": 1,
            "total": 16000000
        }
    ],
    "ship": 0,
    "total": 21005000,
    "payment": 1
}


###
POST http://localhost:4000/order/pay
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsImRpc3RyaWN0Ijo1LCJwcm92aW5jZSI6NCwid2FyZCI6NiwiY2FydCI6W10sIndpc2giOltdfSwiaWF0IjoxNjU4NDM1ODkzLCJleHAiOjE2NTg2MDg2OTN9.6xtoNqlHFtyj9pEgxEXRxZAX-Zc7rqc87rf144eo4qQ
Content-Type: application/json

{ 
   "id": "62dac03ef0f98bd5ddb65cb1"
}