POST https://fit-summer-2022-ecommerce.herokuapp.com/auth/login
Content-Type: application/json

{ 
    "phone": "0835059053",
    "password": "123" 
}

###

GET http://localhost:4000/auth/test
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJhZjYxZDg2NTYxODA0NTk0MzEzYjJlIiwicGhvbmUiOiIwODM1MDU5MDUzIiwicGFzc3dvcmQiOiIkYXJnb24yaSR2PTE5JG09NDA5Nix0PTMscD0xJCtPcUNPY2E1R3hmV3F2aU44R25JT3ckditNTUNoRjNuOVBSV01TT3BRZmRQc1J2S1IzN01sTXRyemhmOFV5WlNsdyIsInJvbGUiOjF9LCJpYXQiOjE2NTYxNzg0ODUsImV4cCI6MTY1NjM1MTI4NX0.PZQIFeLH9Aa7aWWlZ4z114OUVQnhnqI-a9fwjrGCIfk

###
POST https://fit-summer-2022-ecommerce.herokuapp.com/auth/login
Content-Type: application/json

{ 
    "phone": "123123123123",
    "password": "123" 
}

###
GET http://localhost:4000/user/info
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsIndpc2giOlt7Il9pZCI6IjYyYmM4NjUwMGU2YjM4OTQ5MDE5NTM1NCJ9XSwiZGlzdHJpY3QiOjUsInByb3ZpbmNlIjo0LCJ3YXJkIjo2fSwiaWF0IjoxNjU3ODY3MDc1LCJleHAiOjE2NTgwMzk4NzV9.7t16l7dfdNHq9e5LPjCjze7c94yIgFPo2W1TG1ujsrE

###
GET http://localhost:4000/products/get-list-by-category?category=62ab68801094bceaaaa5c981&page=1

###
GET http://localhost:4000/products/get-product?id=62bd79c9dcccb6ee9faf9cd9


###
POST http://localhost:4000/products/add-product
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IiIsImdlbmRlciI6IiIsImFkZHJlc3MiOiIiLCJjbW5kIjoiIiwicm9sZSI6MSwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsIndpc2giOlt7Il9pZCI6IjYyYmM4NjUwMGU2YjM4OTQ5MDE5NTM1NCJ9XX0sImlhdCI6MTY1NjUyNzY3OSwiZXhwIjoxNjU2NzAwNDc5fQ.R7ZhwMSL_eKw_O-BneeKCLxrDOPS1whHGsBe-y_vbTY
Content-Type: application/json

{ 
    "title": "Phuộc YSS RAIDER/SATRIA G-SPORT", 
    "description": "Phuộc YSS Suzuki RAIDER, SATRIA G-SPORT CÓ BÌNH DẦU. Nhập khẩu chính hãng YSS Thái Lan bởi YSS.VN. Thông Số Phuộc YSS: MX302-285TRL-01-4-JX", 
    "nameBrand": "YSS", 
    "type": [{ "color": "#ffd700", "quantity": 20, "price": 4000000 },{ "color": "#ffd700", "quantity": 20, "price": 5000000 }], 
    "category": "62ab68801094bceaaaa5c981", 
    "image": [] 
}

###
POST http://localhost:4000/user/change-password
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IiIsImdlbmRlciI6IiIsImFkZHJlc3MiOiIiLCJjbW5kIjoiIiwicm9sZSI6MSwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjB9LCJpYXQiOjE2NTY0ODAzMjAsImV4cCI6MTY1NjY1MzEyMH0.0DEsptfmZ-Q6_JiKw87yqu-G_nRXKrpqINTc42v0Maw
Content-Type: application/json

{ 
    "password": "12345" ,
     "newPassword": "1234" 
}


###
POST http://localhost:4000/user/add-wish-product
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsicHJvdmluY2UiOi0xLCJkaXN0cmljdCI6LTEsIndhcmQiOi0xLCJfaWQiOiI2MmI3NTI3NmMxYjg1NjJkY2YzNDIyMmQiLCJwaG9uZSI6IjA4MzUwNTkwNTMiLCJlbWFpbCI6IiIsImZ1bGxuYW1lIjoiUm9zZVB1IiwiZ2VuZGVyIjoiIiwiYWRkcmVzcyI6IiIsImNtbmQiOiIiLCJyb2xlIjoxMDAwLCJiaW8iOiJDaMOgbyBt4burbmcgxJHhur9uIHRyYW5nIGPDoSBuaMOibiB0csOqbiDEkOG7kyBDaMahaSBYZSBj4bunYSB0w7RpISIsInJlY2VpcHQiOltdLCJjcmVhdGVBdCI6IjIwMjItMDYtMjVUMTg6MjI6NDYuMDQyWiIsIl9fdiI6MCwid2lzaCI6W3siX2lkIjoiNjJiYzg2NTAwZTZiMzg5NDkwMTk1MzU0In1dfSwiaWF0IjoxNjU3NTE5OTQ1LCJleHAiOjE2NTc2OTI3NDV9.8xc05pWz5RfBKLDJp_g1G_19VZ3FibMVH-8jeC0KVNY
Content-Type: application/json

{ 
    "idProduct": "62bc86500e6b389490195354"
}

###
POST http://localhost:4000/user/remove-wish-product
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsicHJvdmluY2UiOi0xLCJkaXN0cmljdCI6LTEsIndhcmQiOi0xLCJfaWQiOiI2MmI3NTI3NmMxYjg1NjJkY2YzNDIyMmQiLCJwaG9uZSI6IjA4MzUwNTkwNTMiLCJlbWFpbCI6IiIsImZ1bGxuYW1lIjoiUm9zZVB1IiwiZ2VuZGVyIjoiIiwiYWRkcmVzcyI6IiIsImNtbmQiOiIiLCJyb2xlIjoxMDAwLCJiaW8iOiJDaMOgbyBt4burbmcgxJHhur9uIHRyYW5nIGPDoSBuaMOibiB0csOqbiDEkOG7kyBDaMahaSBYZSBj4bunYSB0w7RpISIsInJlY2VpcHQiOltdLCJjcmVhdGVBdCI6IjIwMjItMDYtMjVUMTg6MjI6NDYuMDQyWiIsIl9fdiI6MCwid2lzaCI6W3siX2lkIjoiNjJiYzg2NTAwZTZiMzg5NDkwMTk1MzU0In1dfSwiaWF0IjoxNjU3NTE5OTQ1LCJleHAiOjE2NTc2OTI3NDV9.8xc05pWz5RfBKLDJp_g1G_19VZ3FibMVH-8jeC0KVNY
Content-Type: application/json

{ 
    "idProduct": "62bc86500e6b389490195354"
}

###
GET  http://localhost:4000/user/wish-list
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsicHJvdmluY2UiOi0xLCJkaXN0cmljdCI6LTEsIndhcmQiOi0xLCJfaWQiOiI2MmI3NTI3NmMxYjg1NjJkY2YzNDIyMmQiLCJwaG9uZSI6IjA4MzUwNTkwNTMiLCJlbWFpbCI6IiIsImZ1bGxuYW1lIjoiUm9zZVB1IiwiZ2VuZGVyIjoiIiwiYWRkcmVzcyI6IiIsImNtbmQiOiIiLCJyb2xlIjoxMDAwLCJiaW8iOiJDaMOgbyBt4burbmcgxJHhur9uIHRyYW5nIGPDoSBuaMOibiB0csOqbiDEkOG7kyBDaMahaSBYZSBj4bunYSB0w7RpISIsInJlY2VpcHQiOltdLCJjcmVhdGVBdCI6IjIwMjItMDYtMjVUMTg6MjI6NDYuMDQyWiIsIl9fdiI6MCwid2lzaCI6W3siX2lkIjoiNjJiYzg2NTAwZTZiMzg5NDkwMTk1MzU0In1dfSwiaWF0IjoxNjU3NTE5OTQ1LCJleHAiOjE2NTc2OTI3NDV9.8xc05pWz5RfBKLDJp_g1G_19VZ3FibMVH-8jeC0KVNY


###
POST http://localhost:4000/user/update-info
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsicHJvdmluY2UiOi0xLCJkaXN0cmljdCI6LTEsIndhcmQiOi0xLCJfaWQiOiI2MmI3NTI3NmMxYjg1NjJkY2YzNDIyMmQiLCJwaG9uZSI6IjA4MzUwNTkwNTMiLCJlbWFpbCI6IiIsImZ1bGxuYW1lIjoiUm9zZVB1IiwiZ2VuZGVyIjoiIiwiYWRkcmVzcyI6IiIsImNtbmQiOiIiLCJyb2xlIjoxMDAwLCJiaW8iOiJDaMOgbyBt4burbmcgxJHhur9uIHRyYW5nIGPDoSBuaMOibiB0csOqbiDEkOG7kyBDaMahaSBYZSBj4bunYSB0w7RpISIsInJlY2VpcHQiOltdLCJjcmVhdGVBdCI6IjIwMjItMDYtMjVUMTg6MjI6NDYuMDQyWiIsIl9fdiI6MCwid2lzaCI6W3siX2lkIjoiNjJiYzg2NTAwZTZiMzg5NDkwMTk1MzU0In1dfSwiaWF0IjoxNjU3NTE5OTQ1LCJleHAiOjE2NTc2OTI3NDV9.8xc05pWz5RfBKLDJp_g1G_19VZ3FibMVH-8jeC0KVNY
Content-Type: application/json

{ 
   "email": "",
    "fullname": "Hồng Phúc",
    "gender": "Nam",
    "address": "37loe",
    "province": 2,
    "district": 3,
    "ward": 4,
    "cmnd": ""
}

###
post http://localhost:4000/pay