###
POST http://localhost:4000/user/add-cart
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsIndpc2giOlt7Il9pZCI6IjYyYmM4NjUwMGU2YjM4OTQ5MDE5NTM1NCJ9XSwiZGlzdHJpY3QiOjUsInByb3ZpbmNlIjo0LCJ3YXJkIjo2LCJjYXJ0IjpbXX0sImlhdCI6MTY1ODIyNDU4MiwiZXhwIjoxNjU4Mzk3MzgyfQ.H1QIjY5uVgeCF7g-4ebH3UFz18SoTO60fJ-o2cFTv3I
Content-Type: application/json

{ 
    "product_id": "62bd79c9dcccb6ee9faf9cd9",
    "type_id": "62bd79c9dcccb6ee9faf9cdb",
    "quantity": 1
}


###
POST http://localhost:4000/user/remove-cart
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsIndpc2giOlt7Il9pZCI6IjYyYmM4NjUwMGU2YjM4OTQ5MDE5NTM1NCJ9XSwiZGlzdHJpY3QiOjUsInByb3ZpbmNlIjo0LCJ3YXJkIjo2LCJjYXJ0IjpbXX0sImlhdCI6MTY1ODIyNDU4MiwiZXhwIjoxNjU4Mzk3MzgyfQ.H1QIjY5uVgeCF7g-4ebH3UFz18SoTO60fJ-o2cFTv3I
Content-Type: application/json

{ 
    "cart_id": "62d6dce7e6d91f082933d57c"
}

###
POST http://localhost:4000/user/remove-wish-product
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiJwaHVjdGhhaTAxMDhAZ21haWwuY29tIiwiZnVsbG5hbWUiOiJSb3VzZVB1IiwiZ2VuZGVyIjoiTmFtIiwiYWRkcmVzcyI6IjM3bG9lIiwiY21uZCI6IiIsInJvbGUiOjEwMDAsImJpbyI6IkNow6BvIG3hu6tuZyDEkeG6v24gdHJhbmcgY8OhIG5ow6JuIHRyw6puIMSQ4buTIENoxqFpIFhlIGPhu6dhIHTDtGkhIiwicmVjZWlwdCI6W10sImNyZWF0ZUF0IjoiMjAyMi0wNi0yNVQxODoyMjo0Ni4wNDJaIiwiX192IjowLCJkaXN0cmljdCI6MTQ0OCwicHJvdmluY2UiOjIwMiwid2FyZCI6MjA2MDcsImNhcnQiOltdLCJ3aXNoIjpbXX0sImlhdCI6MTY1ODkyMzU3NywiZXhwIjoxNjU5MDk2Mzc3fQ.rJtKbfMEqM5FQNZtZ6TZLSMMwu0ez0EvzdRZev9mT7U
Content-Type: application/json
{
    "product_id": "62bc86500e6b389490195354"
}

###
POST http://localhost:4000/user/add-wish-product
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IlJvdXNlUHUiLCJnZW5kZXIiOiJOYW0iLCJhZGRyZXNzIjoiMzdsb2UiLCJjbW5kIjoiIiwicm9sZSI6MTAwMCwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjAsIndpc2giOlt7Il9pZCI6IjYyYmM4NjUwMGU2YjM4OTQ5MDE5NTM1NCJ9XSwiZGlzdHJpY3QiOjUsInByb3ZpbmNlIjo0LCJ3YXJkIjo2LCJjYXJ0IjpbXX0sImlhdCI6MTY1ODIyNDU4MiwiZXhwIjoxNjU4Mzk3MzgyfQ.H1QIjY5uVgeCF7g-4ebH3UFz18SoTO60fJ-o2cFTv3I
Content-Type: application/json

{ 
    "product_id": "62bc86500e6b389490195354"
}


###
POST http://localhost:4000/user/check-exist-user
Content-Type: application/json

{ 
    "phone": "0835059053"
}
