POST https://fit-summer-2022-ecommerce.herokuapp.com/auth/login
Content-Type: application/json

{ 
    "phone": "0835059053",
    "password": "123" 
}

###

GET http://localhost:4000/auth/test
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJhZjYxZDg2NTYxODA0NTk0MzEzYjJlIiwicGhvbmUiOiIwODM1MDU5MDUzIiwicGFzc3dvcmQiOiIkYXJnb24yaSR2PTE5JG09NDA5Nix0PTMscD0xJCtPcUNPY2E1R3hmV3F2aU44R25JT3ckditNTUNoRjNuOVBSV01TT3BRZmRQc1J2S1IzN01sTXRyemhmOFV5WlNsdyIsInJvbGUiOjF9LCJpYXQiOjE2NTYxNzg0ODUsImV4cCI6MTY1NjM1MTI4NX0.PZQIFeLH9Aa7aWWlZ4z114OUVQnhnqI-a9fwjrGCIfk

###
POST https://fit-summer-2022-ecommerce.herokuapp.com/auth/login
Content-Type: application/json

{ 
    "phone": "123123123123",
    "password": "123" 
}

###
GET http://localhost:4000/user/info
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2RhdGEiOnsiX2lkIjoiNjJiNzUyNzZjMWI4NTYyZGNmMzQyMjJkIiwicGhvbmUiOiIwODM1MDU5MDUzIiwiZW1haWwiOiIiLCJmdWxsbmFtZSI6IiIsImdlbmRlciI6IiIsImFkZHJlc3MiOiIiLCJjbW5kIjoiIiwicm9sZSI6MSwiYmlvIjoiQ2jDoG8gbeG7q25nIMSR4bq_biB0cmFuZyBjw6EgbmjDom4gdHLDqm4gxJDhu5MgQ2jGoWkgWGUgY-G7p2EgdMO0aSEiLCJyZWNlaXB0IjpbXSwiY3JlYXRlQXQiOiIyMDIyLTA2LTI1VDE4OjIyOjQ2LjA0MloiLCJfX3YiOjB9LCJpYXQiOjE2NTYyNDM5NzIsImV4cCI6MTY1NjQxNjc3Mn0.b4RtuF7eP5lcOsLa8Y8mR5FcIkWr4Z5jc_GYsC2BLGY

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{ 
    "phone": "0835059053",
    "password": "1234" 
}

###
GET http://localhost:4000/products/getListByCategory?category=62ab68801094bceaaaa5c981


